version: "3.8"
services: 
  back:
    build: .
    container_name: back
    networks:
      - web_net
    ports:
     - "5000:5000"
    depends_on: 
      - db
    volumes:
      - ${PWD}/files:/files
  db: 
    container_name: entrega1-db
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a123
      POSTGRES_DB: entrega1-db
    image: "postgres:latest"
    networks:
      - web_net
    ports: 
      - "5432:5432"
    volumes: 
      - ${PWD}/postgres-data:/var/lib/postgresql/data

networks:
    web_net:
        driver: bridge

volumes: 
  pg-data: 
    driver: local